#!/bin/bash

# printfdemo
# author: jhepworth
# date: Sun Apr  1 08:47:50 UTC 2018
# 
printf "hello" # prints on the same line

printf "\n"

printf "hello\n" # now similar to echo, prints a new line after

printf "hello %s, how are you?\n" $USER # use a variable to say hi to the user

printf "p%st\n" a e i o u # multiple vars



